<?xml version="1.0" encoding="UTF-8"?>
<ActionCollection version="2" name="Scripts">
  <Actions category="Scripts">
    <text>Export Selected Layer</text>
    <Action name="export_selected_layer">
      <icon></icon>
      <text>Export Selected Layer</text>
      <whatsThis>Export Selected Layer wahtsThis</whatsThis>
      <toolTip>Export Selected Layer Tooltip</toolTip>
      <iconText></iconText>
      <activationFlags></activationFlags>
      <activationConditions></activationConditions>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
  </Actions>
</ActionCollection>
